# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63196b0b7c0bd6cf2346807d431259aa596386f5eb504355942e65932c056f0e9266d47f05b5e796aa948f3683ee56312eb73403a95b8bdee190220a538daddc

test:
  secret_key_base: 4ac34780d5bc3fb3e3e6d1f497a286b2c53896917fffb850d8c2e07df59fd7afd393b8a48f4a515ab3644cb7ea05eb06e275a7c05389764188094a46a092318b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
